apiVersion: v1
kind: Service
metadata:
  name: flask-hello-docker
spec:
  selector:
    app: flask-hello-docker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001
  type: LoadBalancer
